### ISSUE TITLE
Installation script should just use `python`

### ISSUE THREAD

**Issue by valencik** [scalacenter/homebrew-bloop#1]
We should make the install script work with either Python 2 or 3 so anyone can install as long as they have some python available.

https://github.com/scalacenter/homebrew-bloop/blob/master/bloop.rb#L14

The install script shebang should also change to use any available python version:
https://github.com/scalacenter/bloop/blob/master/bin/install.py#L1

**Comment by valencik** [comment]
Closing as this has been fixed in the M6 release.

**Comment by joprice** [comment]
I think it would be better if it didn't use python at all. I can never seem to find an environment where the python installation is stable. I haven't been able to try this tool out yet due to this error `Couldn't download https://git.io/vgvpD, please try again.`.  Turns out, after digging into it, it's some kind of ssl regression caused by upgrading XCode. Is there anyway the installation script could be rewritten using ammonite or a plain scala?

**Comment by jvican** [comment]
> Is there anyway the installation script could be rewritten using ammonite or a plain scala?

In theory it's possible. But bloop requires Python anyway because the Nailgun client is written in Python, so it doesn't seem there will be much to gain from rewriting the installation script in Scala.

**Comment by joprice** [comment]
I see. That's unfortunate. I guess I gotta try to charge those batteries they included.
